/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Window.java
 *
 * Created on Oct 1, 2009, 11:21:40 AM
 */

package onedimensionautomata;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author x00875
 */
public class Window extends javax.swing.JFrame {

    /** Creates new form Window */
    public Window() {
        initComponents();
        jButton1ActionPerformed(null);
        final WorldConnectionMatrix wcm = new WorldConnectionMatrix(worldView1.getData().get(0));
        connectTab.setData(wcm.getData());
        connectTab.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                Point click = connectTab.rowCol;
                wcm.toggleConnection(click.y, click.x);
                ((World)worldView1.getData().get(0)).topology = wcm;
                connectTab.repaint();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        generation = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        size = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        worldView1 = new onedimensionautomata.WorldView();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        connectTab = new onedimensionautomata.WorldView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(65655, 23));

        jButton1.setText("Start");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        generation.setValue(5);
        jToolBar1.add(generation);

        jLabel1.setText("Generations");
        jToolBar1.add(jLabel1);

        size.setValue(20);
        jToolBar1.add(size);

        jLabel2.setText("Size");
        jToolBar1.add(jLabel2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        worldView1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                worldView1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(worldView1);

        jTabbedPane1.addTab("Graphic", jScrollPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTabbedPane1.addTab("Count Table", jScrollPane2);
        jTabbedPane1.addTab("Connections", connectTab);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int s = (Integer) size.getValue();
        int g = (Integer) generation.getValue();
        ArrayList<World> history = Main.runSimulation(g, s, new Rules());
        worldView1.setData(history);
        Integer[][] countHistory = new Integer[g][history.get(0).nstates];
        for (int i = 0; i < g; i++) {
            countHistory[i] = history.get(i).countStates();
        }
        Integer[] colNames = {1, 2, 3, 4};
        jTable1.setModel(new DefaultTableModel(countHistory, colNames));


    //jTextArea1.getDocument().
    }//GEN-LAST:event_jButton1ActionPerformed

    private void worldView1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_worldView1MouseClicked
        Point click = worldView1.rowCol;
        int g = (Integer) generation.getValue();
        //System.out.println(click);
        if (click.y == 0) {
            World w = (World) worldView1.getData().get(0);
            w.setWorldValue(
                    click.x,
                    (w.getWorld()[click.x] + 1) % w.getMaxState());
            // set initial condition in main, and run
            ArrayList<World> history = Main.run(w, g, new Rules());
            System.out.println(history.size());
            worldView1.setData(history);
            Integer[][] countHistory = new Integer[g][w.nstates];
            for (int i = 0; i < g; i++) {
                countHistory[i] = history.get(i).countStates();
            }
            Integer[] colNames = {1, 2, 3, 4};
            jTable1.setModel(new DefaultTableModel(countHistory,colNames));
            repaint();
        // copy counts to table
        }
    }//GEN-LAST:event_worldView1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private onedimensionautomata.WorldView connectTab;
    private javax.swing.JSpinner generation;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner size;
    private onedimensionautomata.WorldView worldView1;
    // End of variables declaration//GEN-END:variables

}
